[package]
name = "voudp-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
voudp = { path = "../voudp" }
eframe = "0.27"
egui = "0.27"
log = "0.4"
pretty_env_logger = "0.5"
anyhow = "1.0"
chrono = "0.4.41"
