[package]
name = "voudp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.0"
chrono = "0.4.41"
clap = { version = "3.0", features = ["derive"] }
cpal = "0.15"
log = "0.4.27"
opus = "0.3.0"
pretty_env_logger = "0.5.0"
ringbuf = "0.4.8"
symphonia = "0.5.4"
