[package]
name = "voudp-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
voudp = { path = "../voudp" }
log = "0.4"
pretty_env_logger = "0.5"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"