name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ALSA dependencies
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev

    - name: Build project
      run: cargo build --release
